### ISSUE TITLE
yesod add-handler brokes building

### ISSUE THREAD

**Issue by alexanderlobov** [yesodweb/yesod#1288]
Hi!

I'm just trying to reproduce steps from [Yesod quick start guide](http://www.yesodweb.com/page/quickstart) and [this tutorial](http://yannesposito.com/Scratch/en/blog/Yesod-tutorial-for-newbies/)

```
alex@alex-comp:~/src/haskell/try-yesod$ stack new faulty-add-handler yesod-sqlite
Downloading template "yesod-sqlite" to create project "faulty-add-handler" in faulty
-add-handler/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- faulty-add-handler/faulty-add-handler.cabal

Selecting the best among 9 snapshots...

* Rejected lts-7.5
    ghc-8.0.1 cannot be used for these packages:
        - faulty-add-handler
    base version 4.9.0.0 found
        - faulty-add-handler requires >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
    Using package flags:
        - faulty-add-handler: dev = False, library-only = False

Downloaded nightly-2016-10-22 build plan.    
* Rejected nightly-2016-10-22
    ghc-8.0.1 cannot be used for these packages:
        - faulty-add-handler
    base version 4.9.0.0 found
        - faulty-add-handler requires >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
    Using package flags:
        - faulty-add-handler: dev = False, library-only = False

* Matches lts-6.23

Selected resolver: lts-6.23
Initialising configuration using resolver: lts-6.23
Total number of user packages considered: 1
Writing configuration to file: faulty-add-handler/stack.yaml
All done.

alex@alex-comp:~/src/haskell/try-yesod$ cd faulty-add-handler/
alex@alex-comp:~/src/haskell/try-yesod/faulty-add-handler$ stack build yesod-bin cab
al-install --install-ghc
alex@alex-comp:~/src/haskell/try-yesod/faulty-add-handler$ stack build
...
stack exec -- yesod devel
```

At this point everything works fine.

Then,

```
alex@alex-comp:~/src/haskell/try-yesod/faulty-add-handler$ yesod add-handler
yesod add-handler
Name of route (without trailing R): Echo
Enter route pattern (ex: /entry/#EntryId): /echo/#String
Enter space-separated list of methods (ex: GET POST): GET

alex@alex-comp:~/src/haskell/try-yesod/faulty-add-handler$ stack build 
...
/home/alex/src/haskell/try-yesod/faulty-add-handler/.stack-work/dist/x86_64-linux/Ca
bal-1.22.5.0/build/libHSfaulty-add-handler-0.0.0-DyJSdKn9LYs27Cs5xSRT2N.a(Applicatio
n.o):(.data+0x390): undefined reference to `faultzuDyJSdKn9LYs27Cs5xSRT2N_HandlerziE
cho_getEchoR_closure'
collect2: error: ld returned 1 exit status

If the above build failed with a linker error or .so/DLL error, addressing these may
 help:
Warning: module not listed in faulty-add-handler.cabal for library component (add to
 other-modules): Handler.Echo
```

There are two issues:
- No `Handler.Echo` string in cabal file in library's `exposed-modules` section
- Wrong error message. It says "add to other-modules". Correct is "add to exposed-modules".

**Comment by psibi** [comment]
What version of yesod are you using ? IIRC, this was fixed recently: https://github.com/yesodweb/yesod/issues/1273

**Comment by alexanderlobov** [comment]
#1273 seems to be the same bug.

But it should be fixed in yesod-bin-1.4.18.3

It seems that I use a newer version:

```
alex@alex-comp:~/.stack$ ls precompiled/x86_64-linux/ghc-7.10.3/1.22.5.0/ | grep yes
od-bin
yesod-bin-1.4.18.7
```

But I'm not sure how to detect the version correctly. What I did:

```
alex@alex-comp:~/src/haskell/try-yesod/yosog$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

Then found corresponding version in ~/.stack

```
alex@alex-comp:~/.stack$ ls precompiled/x86_64-linux/ghc-7.10.3/1.22.5.0/ | grep yes
od-bin
yesod-bin-1.4.18.7
```

Also I see the same version on [Stackage description of lts-6.23](https://www.stackage.org/lts-6.23)

What is the right way to find the yesod-bin version?

**Comment by psibi** [comment]
Go inside your project and do this:

```
@sibi::jane { ~/github/chow }-> stack exec -- yesod version
yesod-bin version: 1.4.18.3
```

**Comment by alexanderlobov** [comment]
I switched version to 1.4.18.3, as recommended in #1273 
```
alex@alex-comp:~/src/haskell/try-yesod/yosog$ stack build yesod-bin-1.4.18.3
alex@alex-comp:~/src/haskell/try-yesod/yosog$ stack exec -- yesod version
yesod-bin version: 1.4.18.3
```
The bug is still here
```
alex@alex-comp:~/src/haskell/try-yesod/yosog$ yesod add-handler
Name of route (without trailing R): Foo
Enter route pattern (ex: /entry/#EntryId): /foo
Enter space-separated list of methods (ex: GET POST): GET

/home/alex/src/haskell/try-yesod/yosog/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSyosog-0.0.0-L0QjMBNTnTG0Cr4KdThgTO.a(Application.o):(.data+0x1270): undefined reference to `yosogzuL0QjMBNTnTG0Cr4KdThgTO_HandlerziFoo_getFooR_closure'
collect2: error: ld returned 1 exit status
```

**Comment by amitaibu** [comment]
Sounds related to #1273 - Is your handler added under the test stanza in the cabal file?

**Comment by amitaibu** [comment]
Oh sorry, I see you already mentioned this issue in your comments.

**Comment by psibi** [comment]
@amitaibu Can you confirm if this works for you in the new version ?

**Comment by amitaibu** [comment]
I've updated to `yesod-bin-1.4.18.7` and I can confirm it does not work. Handler is added under `test-suite test`

**Comment by snoyberg** [comment]
I just tested this on my machine with 1.4.18.7, and was unable to reproduce with a cleanly scaffolded yesod-sqlite site.

**Comment by alexanderlobov** [comment]
The root of the issue is that I used system yesod

```
yesod add-handler
```

instead of stack yesod

```
stack exec -- yesod add-handler
```

Thanks for help :)

**Comment by amitaibu** [comment]
I'm still seeing this, even with `stack exec -- yesod add-handler`

**Comment by amitaibu** [comment]
(tested on https://github.com/gizra/yesoders if the repo is somehow related)

**Comment by snoyberg** [comment]
I can't reproduce:

```
diff --git a/yesod-postgres.cabal b/yesod-postgres.cabal
index 08b38ec..130780f 100644
--- a/yesod-postgres.cabal
+++ b/yesod-postgres.cabal
@@ -27,6 +27,7 @@ library
                      Handler.Home
                      Handler.Sitemap
                      Handler.User
+                     Handler.Foo
                      Utils.Flag
                      Utils.LocalTasks
```
